services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Abenmada\ExportPlugin\:
        resource: '../../*'
        exclude: '../../{Service}'

imports:
    - { resource: "packages/service.yaml" }
    - { resource: "packages/action.yaml" }
    - { resource: "packages/grid.yaml" }
    - { resource: "packages/command.yaml" }
